version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo in the pre build phase...
  build:
    commands:
      - echo build started on date...
      - mvn package
  post_build:
    commands:
      - echo completed on date...
artifacts:
  files:
    - target/customer-payments-0.0.1-SNAPSHOT.jar
  discard-paths: yes